### ISSUE TITLE
DKMS build nvidia on linux50

### ISSUE THREAD

**Issue by ryanmusante** [Tk-Glitch/PKGBUILDS#133]
I can't build DKMS nvidia without error. So I am forced to choose regular. What am I doing wrong?

**/var/lib/dkms/nvidia/396.54.09/build/make.log**
```
/var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-encoder.c: In function ‘nv_drm_add_encoder’:
/var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-encoder.c:219:11: error: implicit declaration of function ‘drm_mode_connector_attach_encoder’; did you mean ‘drm_connector_attach_encoder’? [-Werror=implicit-function-declaration]
     ret = drm_mode_connector_attach_encoder(connector, encoder);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           drm_connector_attach_encoder
  CC [M]  /var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-helper.o
/var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-connector.c: In function ‘nv_drm_connector_get_modes’:
/var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-connector.c:229:9: error: implicit declaration of function ‘drm_mode_connector_update_edid_property’; did you mean ‘drm_connector_update_edid_property’? [-Werror=implicit-function-declaration]
         drm_mode_connector_update_edid_property(
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         drm_connector_update_edid_property
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:277: /var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-encoder.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:277: /var/lib/dkms/nvidia/396.54.09/build/nvidia-drm/nvidia-drm-connector.o] Error 1
make[1]: *** [Makefile:1557: _module_/var/lib/dkms/nvidia/396.54.09/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.0.1-3-tkg-pds/build'
make: *** [Makefile:79: modules] Error 2

```

**Comment by ronoverdrive** [comment]
396.xx.xx won't work on Kernel 5.0.x last I checked unless there's been a patch for it. I recommend using Tk-Glitch's Nvidia-All PKGBUILD to install the latest nvidia vulkan driver as there's no reason to use the 396.xx drivers anymore. The 418.xx series officially supports kernel 5.0.x.

**Comment by ryanmusante** [comment]
There is definitely good reason to. https://github.com/Tk-Glitch/PKGBUILDS/issues/112

396.XX works fine installing in regular mode, the problem is when I try to use DKMS install.
