### ISSUE TITLE
NVIDIA's stable driver modules won't compile on LTS kernel; dev driver works

### ISSUE THREAD

**Issue by guihkx** [Tk-Glitch/PKGBUILDS#467]
I was able to build and install the nvidia-all package just fine, but when I try to build the DKMS modules, this error shows up in the terminal:

```
$ sudo dkms autoinstall -k 4.19.98-1-lts
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j4 IGNORE_PREEMPT_RT_PRESENCE=1 NV_EXCLUDE_BUILD_MODULES='__EXCLUDE_MODULES' KERNEL_UNAME=4.19.98-1-lts IGNORE_CC_MISMATCH='__IGNORE_CC_MISMATCH' modules.............(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.98-1-lts (x86_64)
Consult /var/lib/dkms/nvidia/440.44/build/make.log for more information.
```

Here's the content of `/var/lib/dkms/nvidia/440.44/build/make.log`:

https://gist.github.com/guihkx/5c88b0ef1b3afe258855105459328cce

As I mentioned in the title, compiling the "Vulkan dev" driver (currently 440.48.02) works just fine.

**Comment by Tk-Glitch** [comment]
Found the quirk.
It's due to the 5.4 PRIME patch. You probably have a 5.4 or newer kernel installed next to that LTS kernel and the patch gets applied as a result. I'll fix that. In the meantime setting `_54_prime_fixing_attempt="false"` in `customization.cfg` will fix it.

440.48.02 is not affected because it doesn't need that patch for 5.4+ PRIME support.

**Comment by guihkx** [comment]
Thanks for taking a look at this very quickly!

Unfortunately, disabling that patch had no effect for me. I'm still getting compilation errors when I try to compile the modules. Log:

https://gist.github.com/guihkx/797cc535894ddf2926bcbc1859e0a0a6

Since I'm not sure if I actually did something wrong, here's the output of `makepkg -si`:

https://gist.github.com/guihkx/a86d936c622c1dfd29b61a8869a84092

By the way: Before I tried building the package again, I did a `git pull` and also cleanup the folder (by removing `src/`, `pkg/` and the `*.zst` files)

**Comment by Tk-Glitch** [comment]
Ok the patch is still getting applied so there's probably some broken logic in the script. On it.

**Comment by Tk-Glitch** [comment]
Oof. Found it. Very stupid. Fix incoming.

**Comment by Tk-Glitch** [comment]
Should be fixed by https://github.com/Tk-Glitch/PKGBUILDS/commit/2eb34cbcbb468a59687dbaa41cac7e67aa22409d

**Comment by guihkx** [comment]
Worked like a charm now! Thanks!

Feel free to close this whenever you want.

**Comment by Tk-Glitch** [comment]
Great news :) Thanks for the nice report!
